<?
/**********************************************************************************************
 * Created By : EmmetBytes Software Solutions
 * Created Date : June 10, 2012
 * Email : emmetbytes@gmail.com
 *
 * Copyright : (c) EmmetBytes Software Solutions 2012
 * Product Name : Bon Con Special Info
 * Product Version : 1.0
 * 
 * Important : This is a commercial product by EmmetBytes Software Solutions and 
 *   cannot be modified, redistributed or resold without any written permission 
 *   from EmmetBytes Software Solutions
 **********************************************************************************************/
$sLangCategory = 'EmmetBytes BonConSpecialInfo'; 
$aLangContent = array( 
    'emmetbytes_bon_con_special_info' => 'Dolphin Contents With Special Info', 
    'emmetbytes_bon_con_special_info_single' => 'dolphin content with special info', 
    'emmetbytes_bon_con_special_info_plural' => 'dolphin contents with special info', 
    'emmetbytes_bon_con_special_info_common_info_title_caption' => 'Title', 
    'emmetbytes_bon_con_special_info_common_info_sites_url_caption' => 'Sites Url', 
    'emmetbytes_bon_con_special_info_common_info_author_caption' => 'Author', 
    'emmetbytes_bon_con_special_info_common_info_album_caption' => 'Album', 
    'emmetbytes_bon_con_special_info_common_info_rating_caption' => 'Rating', 
    'emmetbytes_bon_con_special_info_common_info_description_caption' => 'Description', 
    'emmetbytes_bon_con_special_info_common_info_location_caption' => 'Location', 
    'emmetbytes_bon_con_special_info_common_info_tags_caption' => 'Tags', 
    'emmetbytes_bon_con_special_info_common_info_categories_caption' => 'Categories', 
    'emmetbytes_bon_con_special_info_common_info_date_start_caption' => 'Date Start', 
    'emmetbytes_bon_con_special_info_common_info_date_end_caption' => 'Date End', 
    '_emmetbytes_bon_con_special_info_homepage_photo' => 'Public Photos With Special Info', 
    '_emmetbytes_bon_con_special_info_homepage_sites' => 'Recently Added Sites With Special Info', 
    '_emmetbytes_bon_con_special_info_homepage_events' => 'Public Events With Special Info', 
    '_emmetbytes_bon_con_special_info_homepage_blogs' => 'Blogs With Special Info', 
    '_emmetbytes_bon_con_special_info_homepage_blogs_articles' => 'Blogs Articles Bon Con Special Info', 
    '_emmetbytes_bon_con_special_info_homepage_sounds' => 'Public Sounds With Special Info', 
    '_emmetbytes_bon_con_special_info_homepage_videos' => 'Public Videos With Special Info', 
    '_emmetbytes_bon_con_special_info_homepage_files' => 'Public Files With Special Info', 
    '_emmetbytes_bon_con_special_info_homepage_groups' => 'Public Groups With Special Info', 
    '_emmetbytes_bon_con_special_info_profile_own_events' => 'My Events With Special Info', 
    '_emmetbytes_bon_con_special_info_profile_joined_events' => 'Joined Events With Special Info', 
    '_emmetbytes_bon_con_special_info_profile_own_groups' => 'My Groups With Special Info', 
    '_emmetbytes_bon_con_special_info_profile_joined_groups' => 'Joined Groups With Special Info', 
    '_emmetbytes_bon_con_special_info_profile_own_sites' => 'Sites With Special Info', 
    '_emmetbytes_bon_con_special_info_profile_own_blogs' => 'Blog With Special Info', 
    '_emmetbytes_bon_con_special_info_profile_own_photos' => 'Profile Photos With Special Info', 
    '_emmetbytes_bon_con_special_info_profile_own_videos' => 'Profile Videos With Special Info', 
    '_emmetbytes_bon_con_special_info_profile_own_sounds' => 'Profile Sounds With Special Info', 
    '_emmetbytes_bon_con_special_info_upcoming_events' => 'Upcoming Public Event With Special Info', 
    '_emmetbytes_bon_con_special_info_past_events' => 'Past Public Events With Special Info', 
    '_emmetbytes_bon_con_special_info_recent_events' => 'Recently Added Events With Special Info', 
    '_emmetbytes_bon_con_special_info_my_events' => 'My Events With Special Info', 
    '_emmetbytes_bon_con_special_info_recent_groups' => 'Recent Public Groups With Special Info', 
    '_emmetbytes_bon_con_special_info_my_groups' => 'User\'s Group With Special Info', 
    '_emmetbytes_bon_con_special_info_main_recent_sites' => 'Recently Added Public Sites With Special Info', 
    '_emmetbytes_bon_con_special_info_main_featured_sites' => 'Featured Public Sites With Special Info', 
    '_emmetbytes_bon_con_special_info_my_own_sites' => 'My Sites With Special Info', 
    '_emmetbytes_bon_con_special_info_latest_blog_post' => 'Latest Post With Special Info', 
    '_emmetbytes_bon_con_special_info_main_public_photos' => 'Public Photos With Special Info', 
    '_emmetbytes_bon_con_special_info_main_featured_photos' => 'Featured Photos With Special Info', 
    '_emmetbytes_bon_con_special_info_main_favorite_photos' => 'My Favorite Photos With Special Info', 
    '_emmetbytes_bon_con_special_info_main_public_videos' => 'Public Videos With Special Info', 
    '_emmetbytes_bon_con_special_info_main_featured_videos' => 'Featured Videos With Special Info', 
    '_emmetbytes_bon_con_special_info_main_favorite_videos' => 'My Favorite Videos With Special Info', 
    '_emmetbytes_bon_con_special_info_main_public_sounds' => 'Public Sounds With Special Info', 
    '_emmetbytes_bon_con_special_info_main_featured_sounds' => 'Featured Sounds With Special Info', 
    '_emmetbytes_bon_con_special_info_main_favorite_sounds' => 'My Favorite Sounds With Special Info', 
    '_emmetbytes_bon_con_special_info_main_public_files' => 'Public Files With Special Info', 
    '_emmetbytes_bon_con_special_info_main_top_files' => 'Top Files With Special Info', 
    '_emmetbytes_bon_con_special_info_main_featured_files' => 'Featured Files WIth Special Info', 
    '_emmetbytes_bon_con_special_info_main_favorite_files' => 'My Favorite Files With Special Info', 
    'emmetbytes_bon_con_special_info_administration' => 'Boonex Contents With Special Info', 
    'emmetbytes_bon_con_special_info_administration_settings' => 'Settings', 
    'emmetbytes_bon_con_special_info_administration_homepage_settings' => 'Homepage Settings', 
    'emmetbytes_bon_con_special_info_administration_profile_settings' => 'Profile Settings', 
    'emmetbytes_bon_con_special_info_administration_module_pages_settings' => 'Module Pages Settings', 
    '_emmetbytes_bon_con_special_info_homepage_event_form_caption' => 'Public Events With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_profile_my_event_form_caption' => 'My Events With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_profile_joined_event_form_caption' => 'Joined Events With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_upcoming_event_form_caption' => 'Upcoming Public Events With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_past_event_form_caption' => 'Past Public Events With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_recent_event_form_caption' => 'Recently Added Events With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_users_event_form_caption' => 'My Events With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_homepage_group_form_caption' => 'Public Groups With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_profile_my_group_form_caption' => 'My Groups With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_profile_joined_group_form_caption' => 'Joined Groups With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_recent_group_form_caption' => 'Recent Public Groups With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_users_group_form_caption' => 'User\'s Groups With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_homepage_site_form_caption' => 'Recently Added Sites With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_profile_my_site_form_caption' => 'Sites With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_profile_joined_site_form_caption' => 'User\'s Joined Sites Bon Con Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_featured_site_form_caption' => 'Featured Public Sites With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_recent_site_form_caption' => 'Recently Added Public Sites With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_users_site_form_caption' => 'My Sites With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_homepage_blogs_form_caption' => 'Blogs With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_profile_my_blogs_form_caption' => 'Blog With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_latest_blogs_form_caption' => 'Latest Posts With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_homepage_photos_form_caption' => 'Public Photos With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_profile_my_photos_form_caption' => 'Profile Photos With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_public_photos_form_caption' => 'Public Photos With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_favorite_photos_form_caption' => 'My Favorite Photos With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_featured_photos_form_caption' => 'Featured Photos With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_homepage_videos_form_caption' => 'Public Videos With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_profile_my_videos_form_caption' => 'Profile Videos With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_public_videos_form_caption' => 'Public Videos With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_favorite_videos_form_caption' => 'My Favorite Videos With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_featured_videos_form_caption' => 'Featured Videos With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_homepage_sounds_form_caption' => 'Public Sounds With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_profile_my_sounds_form_caption' => 'Profile Sounds With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_public_sounds_form_caption' => 'Public Sounds With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_favorite_sounds_form_caption' => 'My Favorite Sounds With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_featured_sounds_form_caption' => 'Featured Sounds With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_homepage_files_form_caption' => 'Pubic Files With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_public_files_form_caption' => 'Public Files With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_top_files_form_caption' => 'Top Files With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_favorite_files_form_caption' => 'My Favorite Files With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_module_blocks_main_featured_files_form_caption' => 'Featured Files With Special Info Settings', 
    '_emmetbytes_bon_con_special_info_default_tab' => 'Default Tab ', 
    '_emmetbytes_bon_con_special_info_image_height_caption' => 'Information Container Image Height ', 
    '_emmetbytes_bon_con_special_info_image_width_caption' => 'Information Container Image Width ', 
    '_emmetbytes_bon_con_special_info_display_site_url_caption' => 'Display The Sites Url ', 
    '_emmetbytes_bon_con_special_info_display_author_caption' => 'Display The Author ', 
    '_emmetbytes_bon_con_special_info_display_album_caption' => 'Display The Album ', 
    '_emmetbytes_bon_con_special_info_display_rating_caption' => 'Display The Rating ', 
    '_emmetbytes_bon_con_special_info_display_location_caption' => 'Display The Location ', 
    '_emmetbytes_bon_con_special_info_display_tags_caption' => 'Display The Tags', 
    '_emmetbytes_bon_con_special_info_display_categories_caption' => 'Display The Categories', 
    '_emmetbytes_bon_con_special_info_display_date_end_caption' => 'Display The End Date ', 
    '_emmetbytes_bon_con_special_info_display_date_start_caption' => 'Display The Start Date ', 
    '_emmetbytes_bon_con_special_info_display_description_caption' => 'Display The Description ', 
    '_emmetbytes_bon_con_special_info_maximum_description_characters_description' => 'Maximum Number Of Characters For The Description ', 
    '_emmetbytes_bon_con_special_info_admin_submit_caption' => 'SAVE', 
    '_emmetbytes_bon_con_special_info_restricted_access_caption' => 'Restricted Access', 
); 
?>
