<?
/**********************************************************************************************
 * Created By : EmmetBytes Software Solutions
 * Created Date : June 10, 2012
 * Email : emmetbytes@gmail.com
 *
 * Copyright : (c) EmmetBytes Software Solutions 2012
 * Product Name : Boonex Contents Slider
 * Product Version : 1.0
 * 
 * Important : This is a commercial product by EmmetBytes Software Solutions and 
 *   cannot be modified, redistributed or resold without any written permission 
 *   from EmmetBytes Software Solutions
 **********************************************************************************************/
$sLangCategory = 'EmmetBytes BoonexContentsSlider'; 
$aLangContent = array( 
    'emmetbytes_boonex_contents_slider' => 'Dolphin Contents Slider', 
    'emmetbytes_boonex_contents_slider_single' => 'module info block', 
    'emmetbytes_boonex_contents_slider_plural' => 'dolphin contents slider', 
    'emmetbytes_boonex_contents_slider_common_info_title_caption' => 'Title', 
    'emmetbytes_boonex_contents_slider_common_info_sites_url_caption' => 'Sites Url', 
    'emmetbytes_boonex_contents_slider_common_info_author_caption' => 'Author', 
    'emmetbytes_boonex_contents_slider_common_info_album_caption' => 'Album', 
    'emmetbytes_boonex_contents_slider_common_info_rating_caption' => 'Rating', 
    'emmetbytes_boonex_contents_slider_common_info_description_caption' => 'Description', 
    'emmetbytes_boonex_contents_slider_common_info_location_caption' => 'Location', 
    'emmetbytes_boonex_contents_slider_common_info_tags_caption' => 'Tags', 
    'emmetbytes_boonex_contents_slider_common_info_categories_caption' => 'Categories', 
    'emmetbytes_boonex_contents_slider_common_info_date_start_caption' => 'Date Start', 
    'emmetbytes_boonex_contents_slider_common_info_date_end_caption' => 'Date End', 
    '_emmetbytes_boonex_contents_slider_homepage_photo' => 'Public Photos on a slider', 
    '_emmetbytes_boonex_contents_slider_homepage_sites' => 'Recently Added Sites on a slider', 
    '_emmetbytes_boonex_contents_slider_homepage_events' => 'Public Events on a slider', 
    '_emmetbytes_boonex_contents_slider_homepage_blogs' => 'Blogs on a slider', 
    '_emmetbytes_boonex_contents_slider_homepage_blogs_articles' => 'Blogs Articles Boonex Contents Slider', 
    '_emmetbytes_boonex_contents_slider_homepage_sounds' => 'Public Sounds on a slider', 
    '_emmetbytes_boonex_contents_slider_homepage_videos' => 'Public Videos on a slider', 
    '_emmetbytes_boonex_contents_slider_homepage_files' => 'Public Files on a slider', 
    '_emmetbytes_boonex_contents_slider_homepage_groups' => 'Public Groups on a slider', 
    '_emmetbytes_boonex_contents_slider_homepage_ads' => 'Public Ads on a slider', 
    '_emmetbytes_boonex_contents_slider_profile_own_events' => 'My Events on a slider', 
    '_emmetbytes_boonex_contents_slider_profile_joined_events' => 'Joined Events on a slider', 
    '_emmetbytes_boonex_contents_slider_profile_own_groups' => 'My Groups on a slider', 
    '_emmetbytes_boonex_contents_slider_profile_joined_groups' => 'Joined Groups on a slider', 
    '_emmetbytes_boonex_contents_slider_profile_own_sites' => 'Sites on a slider', 
    '_emmetbytes_boonex_contents_slider_profile_own_blogs' => 'Blog on a slider', 
    '_emmetbytes_boonex_contents_slider_profile_own_photos' => 'Profile Photos on a slider', 
    '_emmetbytes_boonex_contents_slider_profile_own_videos' => 'Profile Videos on a slider', 
    '_emmetbytes_boonex_contents_slider_profile_own_sounds' => 'Profile Sounds on a slider', 
    '_emmetbytes_boonex_contents_slider_profile_own_ads' => 'Profile Ads on a slider', 
    '_emmetbytes_boonex_contents_slider_upcoming_events' => 'Upcoming Public Events on a slider', 
    '_emmetbytes_boonex_contents_slider_past_events' => 'Past Public Events on a slider', 
    '_emmetbytes_boonex_contents_slider_recent_events' => 'Recently Added Public Events on a slider', 
    '_emmetbytes_boonex_contents_slider_my_events' => 'My Events Boonex Contents Slider', 
    '_emmetbytes_boonex_contents_slider_recent_groups' => 'Recent Public Groups on a slider', 
    '_emmetbytes_boonex_contents_slider_my_groups' => 'My Groups Boonex Contents Slider', 
    '_emmetbytes_boonex_contents_slider_main_recent_sites' => 'Recently Added Public Sites on a slider', 
    '_emmetbytes_boonex_contents_slider_main_featured_sites' => 'Featured Public Sites on a slider', 
    '_emmetbytes_boonex_contents_slider_my_own_sites' => 'Users Own Sites Boonex Contents Slider', 
    '_emmetbytes_boonex_contents_slider_latest_blog_post' => 'Latest Posts on a slider', 
    '_emmetbytes_boonex_contents_slider_main_public_photos' => 'Public Photos on a slider', 
    '_emmetbytes_boonex_contents_slider_main_featured_photos' => 'Featured Photos on a slider', 
    '_emmetbytes_boonex_contents_slider_main_favorite_photos' => 'My Favorite Photos on a slider', 
    '_emmetbytes_boonex_contents_slider_main_public_videos' => 'Public Videos on a slider', 
    '_emmetbytes_boonex_contents_slider_main_featured_videos' => 'Featured Videos on a slider', 
    '_emmetbytes_boonex_contents_slider_main_favorite_videos' => 'My Favorite Videos on a slider', 
    '_emmetbytes_boonex_contents_slider_main_public_sounds' => 'Public Sounds on a slider', 
    '_emmetbytes_boonex_contents_slider_main_featured_sounds' => 'Featured Sounds on a slider', 
    '_emmetbytes_boonex_contents_slider_main_favorite_sounds' => 'My Favorite Sounds on a slider', 
    '_emmetbytes_boonex_contents_slider_main_public_files' => 'Public Files on a slider', 
    '_emmetbytes_boonex_contents_slider_main_top_files' => 'Top Files on a slider', 
    '_emmetbytes_boonex_contents_slider_main_featured_files' => 'Featured Files on a slider', 
    '_emmetbytes_boonex_contents_slider_main_favorite_files' => 'My Favorite Files on a slider', 
    '_emmetbytes_boonex_contents_slider_main_last_ads' => 'Last Ads on a Slider', 
    'emmetbytes_boonex_contents_slider_administration' => 'Boonex Contents Slider Admin', 
    'emmetbytes_boonex_contents_slider_administration_settings' => 'Settings', 
    'emmetbytes_boonex_contents_slider_administration_homepage_settings' => 'Homepage Settings', 
    'emmetbytes_boonex_contents_slider_administration_profile_settings' => 'Profile Settings', 
    'emmetbytes_boonex_contents_slider_administration_module_pages_settings' => 'Module Pages Settings', 
    '_emmetbytes_boonex_contents_slider_homepage_event_form_caption' => 'Public Events On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_profile_my_event_form_caption' => 'My Events On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_profile_joined_event_form_caption' => 'Joined Events On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_upcoming_event_form_caption' => 'Upcoming Public Events On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_past_event_form_caption' => 'Past Public Events On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_recent_event_form_caption' => 'Recently Added Public Events On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_users_event_form_caption' => 'My Events Page - User\'s Own Events Boonex Contents Slider Settings', 
    '_emmetbytes_boonex_contents_slider_homepage_group_form_caption' => 'Public Groups On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_profile_my_group_form_caption' => 'My Groups On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_profile_joined_group_form_caption' => 'Joined Groups On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_recent_group_form_caption' => 'Recent Public Groups On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_users_group_form_caption' => 'My Groups Page - User\'s Groups Boonex Contents Slider Settings', 
    '_emmetbytes_boonex_contents_slider_homepage_site_form_caption' => 'Recently Added Sites On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_profile_my_site_form_caption' => 'Sites On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_profile_joined_site_form_caption' => 'User\'s Joined Sites Boonex Contents Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_featured_site_form_caption' => 'Featured Public Sites On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_recent_site_form_caption' => 'Recently Added Public Sites On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_users_site_form_caption' => 'My Sites Page - User\'s Sites Boonex Contents Slider Settings', 
    '_emmetbytes_boonex_contents_slider_homepage_blogs_form_caption' => 'Blogs On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_profile_my_blogs_form_caption' => 'Blog On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_latest_blogs_form_caption' => 'Latest Post On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_homepage_photos_form_caption' => 'Public Photos On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_profile_my_photos_form_caption' => 'Profile Photos On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_public_photos_form_caption' => 'Public Photos On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_favorite_photos_form_caption' => 'My Favorite Photos On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_featured_photos_form_caption' => 'Featured Photos On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_homepage_videos_form_caption' => 'Public Videos On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_profile_my_videos_form_caption' => 'Profile Videos On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_public_videos_form_caption' => 'Public Videos On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_favorite_videos_form_caption' => 'My Favorite Videos On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_featured_videos_form_caption' => 'Featured Videos On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_homepage_sounds_form_caption' => 'Public Sounds On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_profile_my_sounds_form_caption' => 'Profile Sounds On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_public_sounds_form_caption' => 'Public Sounds On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_favorite_sounds_form_caption' => 'My Favorite Sounds On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_featured_sounds_form_caption' => 'Featured Sounds On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_homepage_files_form_caption' => 'Public Files On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_public_files_form_caption' => 'Public Files On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_top_files_form_caption' => 'Top Files On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_favorite_files_form_caption' => 'My Favorite Files On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_module_blocks_main_featured_files_form_caption' => 'Featured Files On A Slider Settings', 
    '_emmetbytes_boonex_contents_slider_homepage_ads_form_caption' => 'Public Ads On A Slider',
    '_emmetbytes_boonex_contents_slider_profile_my_ads_form_caption' => 'Profile Ads On A Slider Settings',
    '_emmetbytes_boonex_contents_slider_module_blocks_main_last_ads_form_caption' => 'Last Ads On A Slider Settings',
    '_emmetbytes_boonex_contents_slider_default_tab' => 'Default Tab ', 
    '_emmetbytes_boonex_contents_slider_maximum_numbers_of_datas_caption' => 'Maximum number of datas to be displayed',
    '_emmetbytes_boonex_contents_slider_maximum_numbers_of_title_characters_caption' => 'Maximum number of characters for the title',
    '_emmetbytes_boonex_contents_slider_display_author_caption' => 'Display The Author ', 
    '_emmetbytes_boonex_contents_slider_display_album_caption' => 'Display The Album ', 
    '_emmetbytes_boonex_contents_slider_display_rate_caption' => 'Display The Rate ', 
    '_emmetbytes_boonex_contents_slider_display_fans_count_caption' => 'Display The Fans Count ', 
    '_emmetbytes_boonex_contents_slider_display_comments_count_caption' => 'Display Comments Count ',
    '_emmetbytes_boonex_contents_slider_display_fans_caption_singular' => 'Fan', 
    '_emmetbytes_boonex_contents_slider_display_fans_caption_multiple' => 'Fans', 
    '_emmetbytes_boonex_contents_slider_display_location_caption' => 'Display The Location ', 
    '_emmetbytes_boonex_contents_slider_display_tags_caption' => 'Display The Tags', 
    '_emmetbytes_boonex_contents_slider_display_categories_caption' => 'Display The Categories', 
    '_emmetbytes_boonex_contents_slider_display_date_end_caption' => 'Display The End Date ', 
    '_emmetbytes_boonex_contents_slider_display_rating_caption' => 'Display the Rate',
    '_emmetbytes_boonex_contents_slider_display_site_url_caption' => 'Display the Sites Url',
    '_emmetbytes_boonex_contents_slider_display_ads_price_caption' => 'Display the Ads Price',
    '_emmetbytes_boonex_contents_slider_display_date_start_caption' => 'Display The Start Date ', 
    '_emmetbytes_boonex_contents_slider_display_date_created_caption' => 'Display The Created Date ', 
    '_emmetbytes_boonex_contents_slider_display_views_caption' => 'Display the Views ', 
    '_emmetbytes_boonex_contents_slider_display_size_caption' => 'Display the Size ', 
    '_emmetbytes_boonex_contents_slider_display_length_caption' => 'Display the Length ', 
    '_emmetbytes_boonex_contents_slider_display_description_caption' => 'Display The Description ', 
    '_emmetbytes_boonex_contents_slider_maximum_description_characters_description' => 'Maximum Number Of Characters For The Description ', 
    '_emmetbytes_boonex_contents_slider_display_post_text_caption' => 'Display The Post Text ', 
    '_emmetbytes_boonex_contents_slider_maximum_post_text_characters_description' => 'Maximum Number Of Characters For The Post Text ', 
    '_emmetbytes_boonex_contents_slider_admin_submit_caption' => 'SAVE', 
    '_emmetbytes_boonex_contents_slider_restricted_access_caption' => 'Restricted Access', 
); 
?>
