<?
/************************************************************************************************************
 * EmmetBytes Default Profile Cover
 * Default Profile Cover For Creating New Boonex Modules
 ************************************************************************************************************/

$sLangCategory = 'EmmetBytes ProfileCover';

$aLangContent = array(
    '_sbs_txt_title_emmet_bytes_profile_cover' => 'Profile Cover',
    '_emmet_bytes_profile_cover' => 'Profile Cover',
    '_emmet_bytes_profile_cover_single' => 'Profile Cover',
    '_emmet_bytes_profile_cover_plural' => 'Profile Cover',
    '_emmet_bytes_profile_cover_administration' => 'Profile Cover Administration',
    '_emmet_bytes_profile_cover_administration_settings' => 'Settings',
    '_emmetbytes_profile_cover_insert_background_caption' => 'Insert Cover',
    '_emmetbytes_profile_cover_change_background_caption' => 'Change Cover',
    '_emmetbytes_profile_cover_edit_background_caption' => 'Change Cover',
    '_emmetbytes_profile_cover_upload_background_caption' => 'Upload Photo',
    '_emmetbytes_profile_cover_reposition_background_caption' => 'Reposition Photo',
    '_emmetbytes_profile_cover_remove_background_caption' => 'Remove Photo',
    '_emmetbytes_profile_cover_background_image_size_problem' => 'Please make sure that your image has at least {0}px width and {1}px height',
    '_emmetbytes_profile_cover_background_image_file_size_problem' => 'Please make sure that the size of your image is not greater than {0} bytes',
    '_emmetbytes_profile_cover_background_image_upload_problem' => 'Sorry, something went wrong on uploading the image. Please try again later',
    '_emmetbytes_profile_cover_insert_avatar_caption' => 'Insert Avatar',
    '_emmetbytes_profile_cover_update_info_caption' => 'Update Info',
    '_emmetbytes_profile_cover_remove_friend_caption' => 'Remove Friend',
    '_emmetbytes_profile_cover_add_friend_caption' => 'Add Friend',
    '_emmetbytes_profile_cover_accept_friend_request_caption' => 'Accept Friend Request',
    '_emmetbytes_profile_cover_member_cancel_friend_request' => 'Cancel Friend Request',
    '_emmetbytes_profile_cover_send_message_caption' => 'Send A Message',
    '_emmetbytes_profile_cover_about_caption' => 'About',
    '_emmetbytes_profile_cover_popup_close_caption' => 'Close',
    '_emmetbytes_profile_cover_nickname_caption' => 'Nickname ',
    '_emmetbytes_profile_cover_not_allowed_error' => 'Sorry, but you are not allowed to change this data',
    '_emmetbytes_profile_cover_insert_headline_caption' => 'Insert Your Headline',
    '_emmetbytes_profile_cover_help_headline_caption' => 'Help your friends know your thoughts by adding your headline',
    '_emmetbytes_profile_cover_popup_submit_headline_caption' => 'Add Headline',
    '_emmetbytes_profile_cover_no_headline_problem' => 'Please insert your headline',
    '_emmetbytes_profile_cover_headline_caption' => 'Headline',
    '_emmetbytes_profile_cover_location_caption' => 'From ',
    '_emmetbytes_profile_cover_add_location_caption' => 'Insert Your Location',
    '_emmetbytes_profile_cover_help_location_caption' => 'Help your friends find you by adding your location',
    '_emmetbytes_profile_cover_no_country_problem' => 'Please insert your country',
    '_emmetbytes_profile_cover_no_city_problem' => 'Please insert your city',
    '_emmetbytes_profile_cover_popup_submit_location_caption' => 'Add Location',
    '_emmetbytes_profile_cover_add_birthdate_caption' => 'Insert Your Birthdate',
    '_emmetbytes_profile_cover_no_birthdate_problem' => 'Please insert your birthdate',
    '_emmetbytes_profile_cover_birthdate_caption' => 'Born on ',
    '_emmetbytes_profile_cover_help_birthdate_caption' => 'Help your friends find you by adding your birthdate',
    '_emmetbytes_profile_cover_popup_submit_birthdate_caption' => 'Add Birthdate',
    '_emmetbytes_profile_cover_add_gender_caption' => 'Insert Your Gender',
    '_emmetbytes_profile_cover_no_gender_problem' => 'Please insert your gender',
    '_emmetbytes_profile_cover_gender_caption' => 'Gender ',
    '_emmetbytes_profile_cover_help_gender_caption' => 'Help your friends find you by adding your gender',
    '_emmetbytes_profile_cover_popup_submit_gender_caption' => 'Add Gender',
    '_emmetbytes_profile_cover_add_relationship_caption' => 'Insert Your Relationship Status',
    '_emmetbytes_profile_cover_no_relationship_problem' => 'Please insert your relationship',
    '_emmetbytes_profile_cover_relationship_caption' => 'Relationship Status',
    '_emmetbytes_profile_cover_help_relationship_caption' => 'Help your friends find you by adding your relationship status',
    '_emmetbytes_profile_cover_popup_submit_relationship_caption' => 'Add Relationship Status',
    '_emmetbytes_profile_cover_friends_count_caption' => 'Friends <span class="ebytes_profile_cover_member_activity_counter">{0}</span>',
    '_emmetbytes_profile_cover_photo_albums_count_caption' => 'Photo Albums <span class="ebytes_profile_cover_member_activity_counter">{0}</span>',
    '_emmetbytes_profile_cover_video_albums_count_caption' => 'Video Albums <span class="ebytes_profile_cover_member_activity_counter">{0}</span>',
    '_emmetbytes_profile_cover_sound_albums_count_caption' => 'Sound Albums <span class="ebytes_profile_cover_member_activity_counter">{0}</span>',
    '_emmetbytes_profile_cover_file_folders_count_caption' => 'File Folders <span class="ebytes_profile_cover_member_activity_counter">{0}</span>',
    '_emmetbytes_profile_cover_ads_count_caption' => 'Ads <span class="ebytes_profile_cover_member_activity_counter">{0}</span>',
    '_emmetbytes_profile_cover_blogs_count_caption' => 'Blog Posts <span class="ebytes_profile_cover_member_activity_counter">{0}</span>',
    '_emmetbytes_profile_cover_polls_count_caption' => 'Polls <span class="ebytes_profile_cover_member_activity_counter">{0}</span>',
    '_emmetbytes_profile_cover_websites_count_caption' => 'Websites <span class="ebytes_profile_cover_member_activity_counter">{0}</span>',
    '_emmetbytes_profile_cover_events_count_caption' => 'Events <span class="ebytes_profile_cover_member_activity_counter">{0}</span>',
    '_emmetbytes_profile_cover_stores_count_caption' => 'Store Products <span class="ebytes_profile_cover_member_activity_counter">{0}</span>',
    '_emmetbytes_profile_cover_groups_count_caption' => 'Groups <span class="ebytes_profile_cover_member_activity_counter">{0}</span>',
    // bof the spy languages
    '_eb_profile_cover_add_spy_post_background' => '<a href={profile_link}>{profile_nick}</a> added a profile cover background',
    '_eb_profile_cover_change_spy_post_background' => '<a href={profile_link}>{profile_nick}</a> changed a profile cover background',
    '_eb_profile_cover_repositioned_spy_post_background' => '<a href={profile_link}>{profile_nick}</a> repositioned a profile cover background',
    '_eb_profile_cover_remove_spy_post_background' => '<a href={profile_link}>{profile_nick}</a> removed a profile cover background',
    '_eb_profile_cover_add_spy_post_thumbnail' => '<a href={profile_link}>{profile_nick}</a> added a profile cover thumbnail',
    '_eb_profile_cover_add_spy_post_thumbnail' => '<a href={profile_link}>{profile_nick}</a> changed a profile cover thumbnail',
    // eof the spy languages
    // bof the wall langauges
    '_eb_profile_cover_add_wall_post_background' => ' added a profile cover background',
    '_eb_profile_cover_change_wall_post_background' => ' changed a profile cover background',
    '_eb_profile_cover_repositioned_wall_post_background' => ' repositioned a profile cover background',
    '_eb_profile_cover_remove_wall_post_background' => ' removed a profile cover background',
    '_eb_profile_cover_add_wall_post_thumbnail' => ' added a profile cover thumbnail',
    '_eb_profile_cover_add_wall_post_thumbnail' => ' changed a profile cover thumbnail',
    // bof the wall langauges
);

?>
