<?
/**********************************************************************************************
 * Created By : EmmetBytes Software Solutions
 * Created Date : June 10, 2012
 * Email : emmetbytes@gmail.com
 *
 * Copyright : (c) EmmetBytes Software Solutions 2012
 * Product Name : Boonex Contents in Realtime
 * Product Version : 1.0
 * 
 * Important : This is a commercial product by EmmetBytes Software Solutions and 
 *   cannot be modified, redistributed or resold without any written permission 
 *   from EmmetBytes Software Solutions
 **********************************************************************************************/
$sLangCategory = 'EmmetBytes BonConInRealtime'; 
$aLangContent = array( 
    'emmetbytes_bon_con_in_realtime' => 'Dolphin Contents In Realtime', 
    'emmetbytes_bon_con_in_realtime_single' => 'dolphin content in realtime', 
    'emmetbytes_bon_con_in_realtime_plural' => 'dolphin contents in realtime', 
    'emmetbytes_bon_con_in_realtime_common_info_title_caption' => 'Title', 
    'emmetbytes_bon_con_in_realtime_common_info_site_url_caption' => 'Site Url', 
    'emmetbytes_bon_con_in_realtime_common_info_author_caption' => 'Author', 
    'emmetbytes_bon_con_in_realtime_common_info_fans_caption' => 'Fans', 
    'emmetbytes_bon_con_in_realtime_common_info_rating_caption' => 'Rating', 
    'emmetbytes_bon_con_in_realtime_common_info_view_caption' => 'Views', 
    'emmetbytes_bon_con_in_realtime_common_info_size_caption' => 'Size', 
    'emmetbytes_bon_con_in_realtime_common_info_length_caption' => 'Length', 
    'emmetbytes_bon_con_in_realtime_common_info_description_caption' => 'Description', 
    'emmetbytes_bon_con_in_realtime_common_info_contents_caption' => 'Contents', 
    'emmetbytes_bon_con_in_realtime_common_info_location_caption' => 'Location', 
    'emmetbytes_bon_con_in_realtime_common_info_date_caption' => 'Date', 
    'emmetbytes_bon_con_in_realtime_common_info_categories_caption' => 'Categories', 
    'emmetbytes_bon_con_in_realtime_common_info_tags_caption' => 'Tags', 
    'emmetbytes_bon_con_in_realtime_common_info_comments_count_caption' => 'Comments', 
    '_emmetbytes_bon_con_in_realtime_homepage_photo' => 'Public Photos in Realtime', 
    '_emmetbytes_bon_con_in_realtime_homepage_sites' => 'Recently Added Sites in Realtime', 
    '_emmetbytes_bon_con_in_realtime_homepage_events' => 'Public Events in Realtime', 
    '_emmetbytes_bon_con_in_realtime_homepage_blogs' => 'Blogs in Realtime', 
    '_emmetbytes_bon_con_in_realtime_homepage_blogs_articles' => 'Blogs Articles in Realtime', 
    '_emmetbytes_bon_con_in_realtime_homepage_sounds' => 'Public Sounds in Realtime', 
    '_emmetbytes_bon_con_in_realtime_homepage_videos' => 'Public Videos in Realtime', 
    '_emmetbytes_bon_con_in_realtime_homepage_files' => 'Public Files in Realtime', 
    '_emmetbytes_bon_con_in_realtime_homepage_groups' => 'Public Groups in Realtime', 
    '_emmetbytes_bon_con_in_realtime_profile_own_events' => 'My Events in Realtime', 
    '_emmetbytes_bon_con_in_realtime_profile_joined_events' => 'Joined Events in Realtime', 
    '_emmetbytes_bon_con_in_realtime_profile_own_groups' => 'My Groups in Realtime', 
    '_emmetbytes_bon_con_in_realtime_profile_joined_groups' => 'Joined Groups in Realtime', 
    '_emmetbytes_bon_con_in_realtime_profile_own_sites' => 'Sites in Realtime', 
    '_emmetbytes_bon_con_in_realtime_profile_own_blogs' => 'Blog in Realtime', 
    '_emmetbytes_bon_con_in_realtime_profile_own_photos' => 'Profile Photos in Realtime', 
    '_emmetbytes_bon_con_in_realtime_profile_own_videos' => 'Profile Videos in Realtime', 
    '_emmetbytes_bon_con_in_realtime_profile_own_sounds' => 'Profile Sounds in Realtime', 
    '_emmetbytes_bon_con_in_realtime_upcoming_events' => 'Upcoming Public Events in Realtime', 
    '_emmetbytes_bon_con_in_realtime_past_events' => 'Past Public Events in Realtime', 
    '_emmetbytes_bon_con_in_realtime_recent_events' => 'Recently Added Public Events in Realtime', 
    '_emmetbytes_bon_con_in_realtime_my_events' => 'My Events in Realtime', 
    '_emmetbytes_bon_con_in_realtime_recent_groups' => 'Recent Public Groups in Realtime', 
    '_emmetbytes_bon_con_in_realtime_my_groups' => 'My Groups in Realtime', 
    '_emmetbytes_bon_con_in_realtime_main_recent_sites' => 'Recently Added Public Sites in Realtime', 
    '_emmetbytes_bon_con_in_realtime_main_featured_sites' => 'Featured Public Sites in Realtime', 
    '_emmetbytes_bon_con_in_realtime_my_own_sites' => 'Users Own Sites in Realtime', 
    '_emmetbytes_bon_con_in_realtime_latest_blog_post' => 'Latest Posts in Realtime', 
    '_emmetbytes_bon_con_in_realtime_main_public_photos' => 'Public Photos in Realtime', 
    '_emmetbytes_bon_con_in_realtime_main_featured_photos' => 'Featured Photos in Realtime', 
    '_emmetbytes_bon_con_in_realtime_main_favorite_photos' => 'My Favorite Photos in Realtime', 
    '_emmetbytes_bon_con_in_realtime_main_public_videos' => 'Public Videos in Realtime', 
    '_emmetbytes_bon_con_in_realtime_main_featured_videos' => 'Featured Videos in Realtime', 
    '_emmetbytes_bon_con_in_realtime_main_favorite_videos' => 'My Favorite Videos in Realtime', 
    '_emmetbytes_bon_con_in_realtime_main_public_sounds' => 'Public Sounds in Realtime', 
    '_emmetbytes_bon_con_in_realtime_main_featured_sounds' => 'Featured Sounds in Realtime', 
    '_emmetbytes_bon_con_in_realtime_main_favorite_sounds' => 'My Favorite Sounds in Realtime', 
    '_emmetbytes_bon_con_in_realtime_main_public_files' => 'Public Files in Realtime', 
    '_emmetbytes_bon_con_in_realtime_main_top_files' => 'Top Files in Realtime', 
    '_emmetbytes_bon_con_in_realtime_main_featured_files' => 'Featured Files in Realtime', 
    '_emmetbytes_bon_con_in_realtime_main_favorite_files' => 'My Favorite Files in Realtime', 
    'emmetbytes_bon_con_in_realtime_administration' => 'Boonex Contents in Realtime', 
    'emmetbytes_bon_con_in_realtime_administration_settings' => 'Settings', 
    'emmetbytes_bon_con_in_realtime_administration_homepage_settings' => 'Homepage Settings', 
    'emmetbytes_bon_con_in_realtime_administration_profile_settings' => 'Profile Settings', 
    'emmetbytes_bon_con_in_realtime_administration_module_pages_settings' => 'Module Pages Settings', 
    '_emmetbytes_bon_con_in_realtime_homepage_event_form_caption' => 'Public Events in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_fetch_type_automatic' => 'Automatic',
    '_emmetbytes_bon_con_in_realtime_fetch_type_new_entries_button' => 'Display New Entries Button',
    '_emmetbytes_bon_con_in_realtime_fetch_type_caption' => 'New Data Fetch Type',
    '_emmetbytes_bon_con_in_realtime_profile_my_event_form_caption' => 'My Events in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_profile_joined_event_form_caption' => 'Joined Events in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_upcoming_event_form_caption' => 'Upcoming Public Events in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_past_event_form_caption' => 'Past Public Events in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_recent_event_form_caption' => 'Recently Added Public Events in Realtime', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_users_event_form_caption' => 'My Events Page - User\'s Own Events in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_homepage_group_form_caption' => 'Public Groups in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_profile_my_group_form_caption' => 'My Groups in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_profile_joined_group_form_caption' => 'Joined Groups in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_recent_group_form_caption' => 'Recent Public Groups in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_users_group_form_caption' => 'My Groups Page - User\'s Groups in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_homepage_site_form_caption' => 'Recently Added Sites in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_profile_my_site_form_caption' => 'Sites in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_profile_joined_site_form_caption' => 'User\'s Joined Sites in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_featured_site_form_caption' => 'Featured Public Sites in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_recent_site_form_caption' => 'Recently Added Public Sites in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_users_site_form_caption' => 'My Sites Page - User\'s Sites in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_homepage_blogs_form_caption' => 'Blogs in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_profile_my_blogs_form_caption' => 'Blog in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_latest_blogs_form_caption' => 'Latest Posts in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_homepage_photos_form_caption' => 'Public Photos in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_profile_my_photos_form_caption' => 'Profile Photos in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_public_photos_form_caption' => 'Public Photos in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_favorite_photos_form_caption' => 'My Favorite Photos in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_featured_photos_form_caption' => 'Featured Photos in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_homepage_videos_form_caption' => 'Pubic Videos in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_profile_my_videos_form_caption' => 'Profile Videos in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_public_videos_form_caption' => 'Public Videos in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_favorite_videos_form_caption' => 'My Favorite Videos in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_featured_videos_form_caption' => 'Featured Videos in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_homepage_sounds_form_caption' => 'Public Sounds in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_profile_my_sounds_form_caption' => 'Profile Sounds in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_public_sounds_form_caption' => 'Public Sounds in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_favorite_sounds_form_caption' => 'My Favorite Sounds in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_featured_sounds_form_caption' => 'Featured Sounds in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_homepage_files_form_caption' => 'Public Files in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_public_files_form_caption' => 'Public Files in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_top_files_form_caption' => 'Top Files in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_favorite_files_form_caption' => 'My Favorite Files in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_module_blocks_main_featured_files_form_caption' => 'Featured Files in Realtime Settings', 
    '_emmetbytes_bon_con_in_realtime_default_tab' => 'Default Tab ', 
    '_emmetbytes_bon_con_in_realtime_maximum_number_of_datas_caption' => 'Maximum Number Of Datas ', 
    '_emmetbytes_bon_con_in_realtime_display_site_url_caption' => 'Display The Sites Url ', 
    '_emmetbytes_bon_con_in_realtime_display_author_caption' => 'Display The Author ', 
    '_emmetbytes_bon_con_in_realtime_display_album_caption' => 'Display The Album ', 
    '_emmetbytes_bon_con_in_realtime_display_rating_caption' => 'Display The Rating ', 
    '_emmetbytes_bon_con_in_realtime_display_location_caption' => 'Display The Location ', 
    '_emmetbytes_bon_con_in_realtime_display_comments_count_caption' => 'Display The Comments Count ', 
    '_emmetbytes_bon_con_in_realtime_display_size_caption' => 'Display The Size ', 
    '_emmetbytes_bon_con_in_realtime_display_length_caption' => 'Display The Length ', 
    '_emmetbytes_bon_con_in_realtime_display_view_caption' => 'Display The View ', 
    '_emmetbytes_bon_con_in_realtime_display_fans_count_caption' => 'Display The Fans Count ', 
    '_emmetbytes_bon_con_in_realtime_display_tags_caption' => 'Display The Tags', 
    '_emmetbytes_bon_con_in_realtime_display_categories_caption' => 'Display The Categories', 
    '_emmetbytes_bon_con_in_realtime_display_date_caption' => 'Display The Date ', 
    '_emmetbytes_bon_con_in_realtime_display_description_caption' => 'Display The Description ', 
    '_emmetbytes_bon_con_in_realtime_maximum_description_characters_description' => 'Maximum Number Of Characters For The Description ', 
    '_emmetbytes_bon_con_in_realtime_display_contents_caption' => 'Display The Contents ', 
    '_emmetbytes_bon_con_in_realtime_maximum_contents_characters_contents' => 'Maximum Number Of Characters For The Contents ', 
    '_emmetbytes_bon_con_in_realtime_admin_submit_caption' => 'SAVE', 
    '_emmetbytes_bon_con_in_realtime_restricted_access_caption' => 'Restricted Access', 
    '_emmetbytes_bon_con_in_realtime_new_entry_count_caption' => 'Refresh Entries', 
    '_emmetbytes_bon_con_in_realtime_removed_entry_count_caption' => 'Refresh Entries', 
    '_emmetbytes_bon_con_in_realtime_go_to_page_caption' => 'Go To The {0} Page', 
    '_emmetbytes_bon_con_in_realtime_go_page_caption' => 'Go To {0} Page', 
    '_emmetbytes_bon_con_in_realtime_go_to_users_events_page_caption' => 'Go To {0}\'s Events Page',
    '_emmetbytes_bon_con_in_realtime_go_to_users_joined_events_page_caption' => 'Go To {0}\'s Joined Events Page',
    '_emmetbytes_bon_con_in_realtime_go_to_users_groups_page_caption' => 'Go To {0}\'s Groups Page',
    '_emmetbytes_bon_con_in_realtime_go_to_users_joined_groups_page_caption' => 'Go To {0}\'s Joined Groups Page',
    '_emmetbytes_bon_con_in_realtime_go_to_users_site_page_caption' => 'Go To {0}\'s Site Page',
    '_emmetbytes_bon_con_in_realtime_go_to_users_blog_posts_page_caption' => 'Go To {0}\'s Blog Posts Page',
    '_emmetbytes_bon_con_in_realtime_go_to_latest_photos_page_caption' => 'Latest Photos',
    '_emmetbytes_bon_con_in_realtime_go_to_users_photos_page_caption' => 'Go To {0}\'s Photos Page',
    '_emmetbytes_bon_con_in_realtime_go_to_latest_videos_page_caption' => 'Latest Videos',
    '_emmetbytes_bon_con_in_realtime_go_to_users_videos_page_caption' => 'Go To {0}\'s Videos Page',
    '_emmetbytes_bon_con_in_realtime_go_to_latest_sounds_page_caption' => 'Latest Sounds',
    '_emmetbytes_bon_con_in_realtime_go_to_users_sounds_page_caption' => 'Go To {0}\'s Sounds Page',
    '_emmetbytes_bon_con_in_realtime_go_to_latest_files_page_caption' => 'Latest Files',
    '_emmetbytes_bon_con_in_realtime_go_to_users_files_page_caption' => 'Go To {0}\'s Files Page',
); 
?>
