<?
/************************************************************************************************************
 * EmmetBytes Default Club Cover
 ************************************************************************************************************/

$sLangCategory = 'EmmetBytes ClubCover';

$aLangContent = array(
    '_sbs_txt_title_emmet_bytes_club_cover' => 'Club Cover',
    '_emmet_bytes_club_cover' => 'Club Cover',
    '_emmet_bytes_club_cover_single' => 'Club Cover',
    '_emmet_bytes_club_cover_plural' => 'Club Cover',
    '_emmet_bytes_club_cover_administration' => 'Club Cover Administration',
    '_emmet_bytes_club_cover_administration_settings' => 'Settings',
    '_emmetbytes_club_cover_insert_background_caption' => 'Insert Cover',
    '_emmetbytes_club_cover_change_background_caption' => 'Change Cover',
    '_emmetbytes_club_cover_edit_background_caption' => 'Change Cover',
    '_emmetbytes_club_cover_upload_background_caption' => 'Upload Photo',
    '_emmetbytes_club_cover_reposition_background_caption' => 'Reposition Photo',
    '_emmetbytes_club_cover_remove_background_caption' => 'Remove Photo',
    '_emmetbytes_club_cover_background_image_size_problem' => 'Please make sure that your image has at least {0}px width and {1}px height',
    '_emmetbytes_club_cover_background_image_file_size_problem' => 'Please make sure that the size of your image is not greater than {0} bytes',
    '_emmetbytes_club_cover_background_image_upload_problem' => 'Sorry, something went wrong on uploading the image. Please try again later',
    '_emmetbytes_club_cover_insert_logo_caption' => 'Insert Logo',
    '_emmetbytes_club_cover_update_info_caption' => 'Update Info',
    '_emmetbytes_club_cover_remove_friend_caption' => 'Remove Friend',
    '_emmetbytes_club_cover_author_info' => "By <a href='{0}'>{1}</a>",
    '_emmetbytes_club_cover_teleport_now' => 'Teleport Now',
    '_emmetbytes_club_cover_about_caption' => 'About',
    '_emmetbytes_club_cover_popup_close_caption' => 'Close',
    '_emmetbytes_club_cover_nickname_caption' => 'Nickname ',
    '_emmetbytes_club_cover_not_allowed_error' => 'Sorry, but you are not allowed to change this data',
    '_emmetbytes_club_cover_not_available_caption' => 'Not Available',
    '_emmetbytes_club_cover_show_more_information_caption' => 'Show More Information',
    '_emmetbytes_club_cover_show_less_information_caption' => 'Show Less Information',
    '_emmetbytes_club_cover_business_website_caption' => '<span>Website :</span> {0}',
    '_emmetbytes_club_cover_insert_business_website_caption' => 'Insert your business website',
    '_emmetbytes_club_cover_business_email_caption' => 'Email : {0}',
    '_emmetbytes_club_cover_business_insert_email_caption' => 'Insert your business email',
    '_emmetbytes_club_cover_business_telephone_caption' => 'Telephone : {0}',
    '_emmetbytes_club_cover_business_insert_telephone_caption' => 'Insert your telephone number',
    '_emmetbytes_club_cover_business_fax_caption' => 'Fax : {0}',
    '_emmetbytes_club_cover_insert_business_fax_caption' => 'Insert your business fax number',
    '_emmetbytes_club_cover_club_capacity_caption' => 'Club Capacity : {0}',
    '_emmetbytes_club_cover_insert_club_capacity_caption' => 'Insert club capacity',
    '_emmetbytes_club_cover_club_charge_caption' => 'Club Charge : {0}',
    '_emmetbytes_club_cover_insert_club_charge_caption' => 'Insert club charge',
    '_emmetbytes_club_cover_club_entry_age_caption' => 'Entry Age : {0}',
    '_emmetbytes_club_cover_insert_club_entry_age_caption' => 'Insert entry age',
    '_emmetbytes_club_cover_club_hours_caption' => 'Hours : {0}',
    '_emmetbytes_club_cover_insert_club_hours_caption' => 'Insert club hours',
    '_emmetbytes_club_cover_club_vip_area_caption' => 'VIP Area : {0}',
    '_emmetbytes_club_cover_insert_club_vip_area_caption' => 'Insert vip area',
    '_emmetbytes_club_cover_club_bar_type_caption' => 'Bar Type : {0}',
    '_emmetbytes_club_cover_insert_club_bar_type_caption' => 'Insert bar type',
    '_emmetbytes_club_cover_club_food_service_caption' => 'Food Service : {0}',
    '_emmetbytes_club_cover_insert_club_food_service_caption' => 'Insert food service',
    '_emmetbytes_club_cover_fans_count_caption' => 'Fans <span class="ebytes_club_cover_addon_data_counter">{0}</span>',
    '_emmetbytes_club_cover_photo_albums_count_caption' => 'Photos <span class="ebytes_club_cover_addon_data_counter">{0}</span>',
    '_emmetbytes_club_cover_video_albums_count_caption' => 'Videos <span class="ebytes_club_cover_addon_data_counter">{0}</span>',
    '_emmetbytes_club_cover_sound_albums_count_caption' => 'Sounds <span class="ebytes_club_cover_addon_data_counter">{0}</span>',
    '_emmetbytes_club_cover_file_folders_count_caption' => 'Files <span class="ebytes_club_cover_addon_data_counter">{0}</span>',
    '_emmetbytes_club_cover_news_count_caption' => 'News <span class="ebytes_club_cover_addon_data_counter">{0}</span>',
    '_emmetbytes_club_cover_website_count_caption' => 'Website <span class="ebytes_club_cover_addon_data_counter">{0}</span>',
    '_emmetbytes_club_cover_events_count_caption' => 'Events <span class="ebytes_club_cover_addon_data_counter">{0}</span>',
    '_emmetbytes_club_cover_popup_submit_business_website_caption' => 'Insert Business Website',
    '_emmetbytes_club_cover_help_business_website_caption' => 'Help your fans find you by adding your website',
    '_emmetbytes_club_cover_business_website_input_caption' => 'Website',
    '_emmetbytes_club_cover_no_business_website_problem' => 'Please enter your business website',
    '_emmetbytes_club_cover_business_website_invalid' => 'The url that you have input seems to be invalid',
    '_emmetbytes_club_cover_popup_submit_business_email_caption' => 'Insert Business Email',
    '_emmetbytes_club_cover_help_business_email_caption' => 'Help your fans find you by adding your email',
    '_emmetbytes_club_cover_business_email_input_caption' => 'Email',
    '_emmetbytes_club_cover_no_business_email_problem' => 'Please enter your business email',
    '_emmetbytes_club_cover_business_email_invalid' => 'The email that you have input seems to be invalid',
    '_emmetbytes_club_cover_popup_submit_business_telephone_caption' => 'Insert Business Telephone',
    '_emmetbytes_club_cover_help_business_telephone_caption' => 'Help your fans find you by adding your telephone',
    '_emmetbytes_club_cover_business_telephone_input_caption' => 'Telephone',
    '_emmetbytes_club_cover_no_business_telephone_problem' => 'Please enter your business telephone',
    '_emmetbytes_club_cover_popup_submit_business_fax_caption' => 'Insert Business Fax',
    '_emmetbytes_club_cover_help_business_fax_caption' => 'Help your fans find you by adding your fax',
    '_emmetbytes_club_cover_business_fax_input_caption' => 'Fax',
    '_emmetbytes_club_cover_no_business_fax_problem' => 'Please enter your business fax',
    '_emmetbytes_club_cover_popup_submit_club_capacity_caption' => 'Insert Club Capacity',
    '_emmetbytes_club_cover_help_club_capacity_caption' => 'Help your fans by adding your club capacity',
    '_emmetbytes_club_cover_club_capacity_input_caption' => 'Club Capacity',
    '_emmetbytes_club_cover_no_club_capacity_problem' => 'Please enter your club capacity',
    '_emmetbytes_club_cover_popup_submit_club_charge_caption' => 'Insert Club Charge',
    '_emmetbytes_club_cover_help_club_charge_caption' => 'Help your fans by adding your club charge',
    '_emmetbytes_club_cover_club_charge_input_caption' => 'Club Charge',
    '_emmetbytes_club_cover_no_club_charge_problem' => 'Please enter your club charge',
    '_emmetbytes_club_cover_popup_submit_club_entry_age_caption' => 'Insert Club Entry Age',
    '_emmetbytes_club_cover_help_club_entry_age_caption' => 'Help your fans by adding your club entry age',
    '_emmetbytes_club_cover_club_entry_age_input_caption' => 'Club Entry Age',
    '_emmetbytes_club_cover_no_club_entry_age_problem' => 'Please enter your club entry age',
    '_emmetbytes_club_cover_popup_submit_club_hours_caption' => 'Insert Club Hours',
    '_emmetbytes_club_cover_help_club_hours_caption' => 'Help your fans by adding your club hours',
    '_emmetbytes_club_cover_club_hours_input_caption' => 'Club Hours',
    '_emmetbytes_club_cover_no_club_hours_problem' => 'Please enter your club hours',
    '_emmetbytes_club_cover_popup_submit_club_vip_area_caption' => 'Insert Club VIP Area',
    '_emmetbytes_club_cover_help_club_vip_area_caption' => 'Help your fans by adding your club vip area',
    '_emmetbytes_club_cover_club_vip_area_input_caption' => 'Club VIP Area',
    '_emmetbytes_club_cover_no_club_vip_area_problem' => 'Please enter your club vip area',
    '_emmetbytes_club_cover_popup_submit_club_bar_type_caption' => 'Insert Club Bar Type',
    '_emmetbytes_club_cover_help_club_bar_type_caption' => 'Help your fans by adding your club bar type',
    '_emmetbytes_club_cover_club_bar_type_input_caption' => 'Club Bar Type',
    '_emmetbytes_club_cover_no_club_bar_type_problem' => 'Please enter your club bar type',
    '_emmetbytes_club_cover_popup_submit_club_food_service_caption' => 'Insert Club Food Service',
    '_emmetbytes_club_cover_help_club_food_service_caption' => 'Help your fans by adding your club food service',
    '_emmetbytes_club_cover_club_food_service_input_caption' => 'Club Food Service',
    '_emmetbytes_club_cover_no_club_food_service_problem' => 'Please enter your club food service',
    '_emmetbytes_club_cover_stream_player_not_available' => 'Stream Player Is Not Available',
    '_emmetbytes_club_cover_stream_player_url_missing_caption' => 'Please enter your stream url',
    '_emmetbytes_club_cover_stream_player_url_invalid_caption' => 'Invalid Url',
    '_emmetbytes_club_cover_stream_player_url_input_caption' => 'Enter your stream url here',
    '_emmetbytes_club_cover_stream_player_form_label' => 'You can also add your stream url here for your club',
    '_emmetbytes_club_cover_views_counter_caption' => '{0} Views',
    // bof the spy languages
    '_eb_club_cover_add_spy_post_background' => '<a href={profile_link}>{profile_nick}</a> added a club cover background',
    '_eb_club_cover_change_spy_post_background' => '<a href={profile_link}>{profile_nick}</a> changed a club cover background',
    '_eb_club_cover_repositioned_spy_post_background' => '<a href={profile_link}>{profile_nick}</a> repositioned a club cover background',
    '_eb_club_cover_remove_spy_post_background' => '<a href={profile_link}>{profile_nick}</a> removed a club cover background',
    '_eb_club_cover_add_spy_post_thumbnail' => '<a href={profile_link}>{profile_nick}</a> added a club cover logo',
    '_eb_club_cover_add_spy_post_thumbnail' => '<a href={profile_link}>{profile_nick}</a> changed a club cover logo',
    // eof the spy languages
    // bof the wall langauges
    '_eb_club_cover_add_wall_post_background' => ' added a club cover background',
    '_eb_club_cover_change_wall_post_background' => ' changed a club cover background',
    '_eb_club_cover_repositioned_wall_post_background' => ' repositioned a club cover background',
    '_eb_club_cover_remove_wall_post_background' => ' removed a club cover background',
    '_eb_club_cover_add_wall_post_thumbnail' => ' added a club cover logo',
    '_eb_club_cover_add_wall_post_thumbnail' => ' changed a club cover logo',
    // bof the wall langauges
);

?>
